name: daw-app

services:
  db:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  adminer:
    image: adminer 
    restart: unless-stopped
    ports:
      - 8080:8080